export const SECTION_LABELS = {
  titles: "Tentative Titles",
  opening_hook: "Opening Hook",
  opening_hook_prompt: "Today you are going to learn...",
  credibility_points: "Credibility Points",
  credibility_points_prompt: "Here's how I know...",
  story_or_quote: "1 Minute Story or Quote",
  key_points: "Key Helpful Points",
  key_points_prompt: "Up to 5 summary points",
  point_details_prefix: "Point",
  point_details_suffix: "Details",
  point_details_prompt: "Teachings, stories, quotes for this point",
  helpful_ending: "Relevant & Helpful Ending",
  revenue_cta: "Revenue CTA",
  revenue_cta_placement: "Revenue CTA Placement",
  shot_list: "Shot List",
  shot_list_prompt: "Shots, scenes, B-roll ideas",
} as const;

export const EMPTY_SCRIPT_FORM = {
  title_1: "",
  title_2: "",
  title_3: "",
  opening_hook: "",
  credibility_points: "",
  story_or_quote: "",
  key_point_1: "",
  key_point_2: "",
  key_point_3: "",
  key_point_4: "",
  key_point_5: "",
  point_1_details: "",
  point_2_details: "",
  point_3_details: "",
  point_4_details: "",
  point_5_details: "",
  helpful_ending: "",
  revenue_cta: "",
  revenue_cta_placement: "",
  shot_1: "",
  shot_2: "",
  shot_3: "",
  shot_4: "",
  shot_5: "",
  shot_6: "",
} as const;
